[tool.poetry]
name = "todo-cli"
version = "0.1.0"
description = ""
authors = ["Ajith Aravind <ajith.aravind100@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = {version = "^6.0", platform = "linux"}
sqlalchemy = {version = "^1.4.45", platform = "linux"}

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"
pylint = "^2.15.9"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 3
